server:
  port: 5031

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080

gridsuite:
  services:
    report-server:
      base-uri: http://localhost:5028

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
