server:
  port: 5031

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080

gridsuite:
  services:
    filter-server:
      base-uri: http://localhost:5027
    report-server:
      base-uri: http://localhost:5028

logging:
  level:
    # please let us debug that server
    org.gridsuite.shortcircuit.server.report: DEBUG
    # helpers logs the same content as the ReportNode tree being constructed: that is noise for us
    com.rte_france.powsybl.iidm.export.adn: ERROR
    com.rte_france.powsybl.courcirc.Courcirc: WARN
