server:
  port: 5031

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

backing-services:
  report-server:
    base-uri: http://localhost:5028
  network-store-server:
    base-uri: http://localhost:8080
