server:
  port: 5031

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

network-store-server:
  base-uri: http://localhost:8080

report-server:
  base-uri: http://localhost:5028
