name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-backend-app-generic.yml@69b162754c0728d9aeb2ea568eaf47f28f60fafb
    with:
      dockerImage: docker.io/gridsuite/shortcircuit-server
      dockerUsername: gridsuiteci
      eventType: shortcircuit_server_updated
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
